---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600


- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - nodejs
    - python-pip
    - python-dev
    - htop
    - git
    - libgmp-dev
    - libpq-dev

- name: Install additional packages
  apt: name={{ item }}
  with_items: packages
  when: packages

- name: Create application group
  group: name={{ group_name }}

- name: Create application user
  user: name={{ user_name }} group={{ group_name }} shell=/bin/bash home={{ user_home_path }}

- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ user_name }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"

- name: Set up authorized_keys for the deploy user
  authorized_key: user="{{ user_name }}" key="{{ lookup('file', item) }}" state=present
  with_fileglob: ../../../../ssh_pubkeys/*

- name: Setup script to read application environment
  template: src=read_environment.sh.j2 dest=/etc/profile.d/read_environment.sh
   # TODO
#  notify:
#    - restart application
#    - restart sidekiq
#    - restart delayed_job
#    - restart resque

- name: Create temp directory
  file: path={{ app_temp_path }} state=directory
  sudo: no

- name: Create profile.d directory
  file: path={{ profile_d_path }} state=directory owner={{ user_name }} group={{ group_name }}

- name: Create ~/.bash_profile which loads all from ~/profile.d
  template: src=bash_profile.j2 dest={{ user_home_path }}/.bash_profile owner={{ user_name }} group={{ group_name }}
