---
- name: Create delayed-job upstart config
  become: true
  template: src=delayed_job-upstart.conf.j2 dest=/etc/init/{{ delayed_job_app_name }}.conf
  when: os_init_system == 'upstart'
  notify: restart delayed_job

- name: Create delayed-job systemd config
  become: true
  template: src=delayed_job-systemd.service.j2 dest=/etc/systemd/system/{{ delayed_job_app_name }}.service
  when: os_init_system == 'systemd'
  notify: restart delayed_job
