---
- name: Create mysql user
  mysql_user: name={{ mysql_db_user }} password={{ mysql_db_password }} priv=*.*:ALL

- name: Create mysql database
  mysql_db: name={{ mysql_db_name }}

#- name: Create config/database.yml
#  template: src=database.yml.j2 dest={{ shared_config_path }}/database.yml owner={{ user_name }} mode=0600 backup=yes
#  when: mysql_orm in ['activerecord', 'sequel', 'datamapper']
