---
- name: Configure puma
  template: src=puma.rb.j2 dest={{ puma_config_path }}

#- name: Install puma
#  command: /bin/bash -l -c 'gem install puma --no-ri --no-rdoc' chdir={{ app_path }}
#  sudo: no

- name: Create puma directories for sockets and pids
  become: true
  file: path={{ app_temp_path }}/{{ item }} state=directory owner={{ user_name }} group={{ group_name }} recurse=yes
  with_items:
    - pids
    - sockets

- name: Create puma upstart config
  become: true
  template: src=puma-upstart.conf.j2 dest=/etc/init/{{ puma_app_name }}.conf
  when: os_init_system == 'upstart'
#  notify: restart application

- name: Create puma systemd config
  become: true
  template: src=puma-systemd.service.j2 dest=/etc/systemd/system/{{ puma_app_name }}.service
  when: os_init_system == 'systemd'
#  notify: restart application

- name: restart puma
  become: true
  service: name={{ puma_app_name }} state=restarted

- name: restart nginx
  become: true
  service: name=nginx state=restarted

- name: Procfile.logs
  template: src=puma-Procfile.logs.j2 dest={{ this_release_path }}/Procfile.logs
