---
- name: Create resque upstart config
  become: true
  template: src=resque-upstart.conf.j2 dest=/etc/init/{{ resque_app_name }}.conf
  when: os_init_system == 'upstart'
  notify: restart resque

- name: Create resque systemd config
  become: true
  template: src=resque-systemd.service.j2 dest=/etc/systemd/system/{{ resque_app_name }}.service
  when: os_init_system == 'systemd'
  notify: restart resque
