---
- hosts: vm
  roles:
    - provision-swap

- hosts: all
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 36000


- hosts: all
  roles:
    - { role: provision-firewall, when: firewall_allowed_ports is defined }
    - { role: provision-base }

- hosts: application:sidekiq:delayed_job:resque
  roles:
    - provision-ruby

- hosts: application
  roles:
    - provision-nginx

- hosts: all
  roles:
    - provision-vim


- hosts: postgresql
  roles:
    - { role: 'provision-postgresql', when: "'postgresql' in databases"}

- hosts: mysql
  roles:
    - { role: 'provision-mysql', when: "'mysql' in databases"}

- hosts: mongodb
  roles:
    - { role: 'provision-mongodb', when: "'mongodb' in databases"}

- hosts: redis
  roles:
    - { role: 'provision-redis', when: "'redis' in databases"}


